name: Test and Build Frontend
'on':
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/test-frontend.yml
  workflow_run:
    workflows:
      - Deploy Infrastructure
    types:
      - completed
env:
  PROJECT_ID: 3ad06c3d-fd0f-4178-b7b0-a3db3c3616c7
  WEBHOOK_SECRET: MHv7y4zE9pXG2wqAFU1cJRt3NZmLkoBd
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
      - name: Build application
        run: |
          cd frontend
          npm run build
      - name: Notify infrastructure provisioning webhook if successful
        if: success()
        run: |
          curl -X POST  https://4914-149-54-36-244.ngrok-free.app/api/deployment/webhook/advance/success/test \
          -H "Content-Type: application/json" \
          -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}" \
          -d '{
          "projectId": "${{ env.PROJECT_ID }}",
          "message": "Infrastructure provisioning succeeded",
          "status": "success"
          }'
      - name: Notify infrastructure provisioning webhook if failed
        if: failure()
        run: |
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          curl -X POST  https://4914-149-54-36-244.ngrok-free.app/api/deployment/webhook/advance/failure/test \
          -H "Content-Type: application/json" \
          -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}"
          -d '{
          "projectId": "${{ env.PROJECT_ID }}",
          "workflowUrl": "'"$WORKFLOW_URL"'",
          "message": "Infrastructure provisioning failed"
          }'
